/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DownloadProgress: typeof import('./src/components/DownloadProgress.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    ProviderCard: typeof import('./src/components/ProviderCard.vue')['default']
  }
}
